translations_group2 = {
    # === LESSON connect-5: Building Instant Rapport ===

    # Headers, paragraphs, keypoints, tips
    'Rapport Is the Bridge Between Stranger and Customer': 'El Rapport Es el Puente Entre Extraño y Cliente',
    'Rapport is that magical moment when a stranger shifts from \'Who is this person talking to me?\' to \'I like this person, I\'ll hear them out.\' It happens fast \u2014 within 30 to 60 seconds \u2014 and once established, it transforms the entire interaction. Without rapport, you\'re a salesperson. With rapport, you\'re a friendly expert they trust.': 'El rapport es ese momento m\u00e1gico cuando un extra\u00f1o pasa de \'\u00bfQui\u00e9n es esta persona que me habla?\' a \'Me cae bien esta persona, le voy a escuchar.\' Sucede r\u00e1pido \u2014 en 30 a 60 segundos \u2014 y una vez establecido, transforma toda la interacci\u00f3n. Sin rapport, eres un vendedor. Con rapport, eres un experto amigable en quien conf\u00edan.',
    'Rapport isn\'t one technique \u2014 it\'s a combination of signals that tell the customer\'s brain: \'This person is safe. This person is like me. This person cares.\' Stack multiple rapport techniques for maximum effect.': 'El rapport no es una sola t\u00e9cnica \u2014 es una combinaci\u00f3n de se\u00f1ales que le dicen al cerebro del cliente: \'Esta persona es segura. Esta persona es como yo. A esta persona le importo.\' Combina m\u00faltiples t\u00e9cnicas de rapport para m\u00e1ximo efecto.',

    # Technique 1: Mirroring
    'Technique 1: Mirroring': 'T\u00e9cnica 1: El Espejo',
    'Mirroring is subtly matching the customer\'s body language, speech pace, energy level, and vocabulary. When done naturally (not mimicry), it creates subconscious similarity. The customer\'s brain registers: \'This person is like me.\'': 'El espejo es emparejar sutilmente el lenguaje corporal, ritmo de habla, nivel de energ\u00eda y vocabulario del cliente. Cuando se hace de forma natural (no mimica), crea una similitud subconsciente. El cerebro del cliente registra: \'Esta persona es como yo.\'',
    'BODY LANGUAGE: If they stand with hands in pockets, relax your arms. If they lean in during the demo, lean in too. Match their posture generally.': 'LENGUAJE CORPORAL: Si se paran con las manos en los bolsillos, relaja tus brazos. Si se inclinan durante la demostraci\u00f3n, incl\u00ednate t\u00fa tambi\u00e9n. Empareja su postura en general.',
    'SPEECH PACE: Fast talker? Speed up slightly. Slow, measured speaker? Slow down. Matching pace creates conversational harmony.': 'RITMO DE HABLA: \u00bfHabla r\u00e1pido? Acelera un poco. \u00bfHabla lento y pausado? Baja el ritmo. Emparejar el ritmo crea armon\u00eda en la conversaci\u00f3n.',
    'ENERGY LEVEL: Enthusiastic customer? Match their enthusiasm. Reserved customer? Warm but calm. Energy mismatch creates discomfort.': 'NIVEL DE ENERG\u00cdA: \u00bfCliente entusiasta? Empareja su entusiasmo. \u00bfCliente reservado? C\u00e1lido pero calmado. El desajuste de energ\u00eda genera incomodidad.',
    'VOCABULARY: If they say \'cream,\' say \'cream.\' If they say \'moisturizer,\' say \'moisturizer.\' Using their words shows you listen.': 'VOCABULARIO: Si dicen \'crema\', di \'crema\'. Si dicen \'hidratante\', di \'hidratante\'. Usar sus palabras demuestra que escuchas.',
    'Mirroring should feel natural, not obvious. Wait 2-3 seconds after they change posture, then shift yours. If they notice you\'re copying them, it backfires completely. Subtlety is everything.': 'El espejo debe sentirse natural, no obvio. Espera 2-3 segundos despu\u00e9s de que cambien de postura, y luego ajusta la tuya. Si se dan cuenta de que los est\u00e1s copiando, tiene el efecto contrario. La sutileza lo es todo.',

    # Technique 2: Name Usage
    'Technique 2: Name Usage': 'T\u00e9cnica 2: Usar el Nombre',
    'A person\'s name is the sweetest sound in any language. When you learn their name, use it naturally 2-3 times during the interaction. Not excessively \u2014 that feels manipulative \u2014 but enough to create personal connection.': 'El nombre de una persona es el sonido m\u00e1s dulce en cualquier idioma. Cuando sepas su nombre, \u00fasalo de forma natural 2-3 veces durante la interacci\u00f3n. No en exceso \u2014 eso se siente manipulador \u2014 pero lo suficiente para crear conexi\u00f3n personal.',
    '\'Maria, come look in the mirror \u2014 you won\'t believe what you see.\' \'So Maria, which option feels better for you?\' \'It was wonderful meeting you, Maria. Enjoy Andorra!\' Three uses: one during the experience, one during the close, one at goodbye. Perfect.': '\'Mar\u00eda, ven a ver el espejo \u2014 no vas a creer lo que ves.\' \'Entonces, Mar\u00eda, \u00bfcu\u00e1l opci\u00f3n se siente mejor para ti?\' \'Fue un placer conocerte, Mar\u00eda. \u00a1Disfruta Andorra!\' Tres usos: uno durante la experiencia, uno durante el cierre, uno en la despedida. Perfecto.',

    # Technique 3: Genuine Compliments
    'Technique 3: Genuine Compliments': 'T\u00e9cnica 3: Cumplidos Genuinos',
    'Compliments work when they\'re SPECIFIC and GENUINE. Generic compliments (\'You\'re beautiful\') feel fake. Specific compliments (\'That emerald scarf brings out your eyes perfectly\') feel observant and real.': 'Los cumplidos funcionan cuando son ESPEC\u00cdFICOS y GENUINOS. Los cumplidos gen\u00e9ricos (\'Eres hermosa\') se sienten falsos. Los cumplidos espec\u00edficos (\'Esa bufanda esmeralda resalta perfectamente tus ojos\') se sienten observadores y reales.',
    'COMPLIMENT CHOICES: Accessories (scarf, watch, bag), grooming (hair, nails, skin), style (color coordination, unique piece), energy (warm smile, confident walk)': 'CUMPLIDA SUS ELECCIONES: Accesorios (bufanda, reloj, bolsa), aseo (cabello, u\u00f1as, piel), estilo (combinaci\u00f3n de colores, pieza \u00fanica), energ\u00eda (sonrisa c\u00e1lida, caminata segura)',
    'AVOID: Physical compliments that could feel inappropriate (body, weight, age-related). Keep it to choices they\'ve MADE, not attributes they were born with.': 'EVITA: Cumplidos f\u00edsicos que puedan sentirse inapropiados (cuerpo, peso, relacionados con la edad). Mant\u00e9nlo en las elecciones que HAN HECHO, no en atributos con los que nacieron.',
    'DELIVERY: Make eye contact, smile, say it warmly, then move on. Don\'t linger on the compliment \u2014 that creates awkwardness.': 'ENTREGA: Haz contacto visual, sonr\u00ede, d\u00edlo c\u00e1lidamente, y sigue adelante. No te quedes en el cumplido \u2014 eso genera incomodidad.',

    # Technique 4: Finding Common Ground
    'Technique 4: Finding Common Ground': 'T\u00e9cnica 4: Encontrar Terreno Com\u00fan',
    'Shared experiences create instant connection. Travelers in Andorra have common ground waiting to be discovered:': 'Las experiencias compartidas crean conexi\u00f3n instant\u00e1nea. Los viajeros en Andorra tienen terreno com\u00fan esperando ser descubierto:',
    'THE LOCATION: \'Is this your first time in Andorra? I love it here \u2014 the mountains are incredible.\'': 'EL LUGAR: \'\u00bfEs tu primera vez en Andorra? Me encanta aqu\u00ed \u2014 las monta\u00f1as son incre\u00edbles.\'',
    'THE WEATHER: \'Beautiful day for shopping! Better than yesterday\'s rain, right?\'': 'EL CLIMA: \'\u00a1Hermoso d\u00eda para comprar! Mejor que la lluvia de ayer, \u00bfo no?\'',
    'SHARED ORIGINS: \'Oh, you\'re from Madrid? I have family there!\' Even distant connections create bonds.': 'OR\u00cdGENES COMPARTIDOS: \'Oh, \u00bferes de Madrid? \u00a1Tengo familia ah\u00ed!\' Incluso las conexiones lejanas crean lazos.',
    'THE EXPERIENCE: \'Everyone who tries this is shocked \u2014 you\'re going to have the same reaction.\' Shared anticipation of the demo result.': 'LA EXPERIENCIA: \'Todos los que prueban esto se sorprenden \u2014 vas a tener la misma reacci\u00f3n.\' La anticipaci\u00f3n compartida del resultado de la demostraci\u00f3n.',

    # Technique 5: Humor
    'Technique 5: Humor': 'T\u00e9cnica 5: Humor',
    'Humor breaks tension, creates positive emotion, and makes you memorable. The key is LIGHT humor \u2014 nothing edgy, political, or potentially offensive. Self-deprecating humor is safest and most disarming.': 'El humor rompe la tensi\u00f3n, crea emoci\u00f3n positiva y te hace memorable. La clave es humor LIGERO \u2014 nada atrevido, pol\u00edtico o potencialmente ofensivo. El humor autocr\u00edtico es el m\u00e1s seguro y el m\u00e1s desarmante.',
    '\'I promise this is worth two minutes of your time. If you don\'t love it, you can tell me I\'m terrible at my job.\' \'Promise not to scream when you see this result \u2014 my last customer actually did, and her husband got jealous.\' Humor makes people smile, and smiling people buy.': '\'Te prometo que esto vale dos minutos de tu tiempo. Si no te encanta, puedes decirme que soy terrible en mi trabajo.\' \'Promete no gritar cuando veas este resultado \u2014 mi \u00faltima cliente en realidad lo hizo, y su esposo se puso celoso.\' El humor hace que la gente sonr\u00eda, y la gente que sonr\u00ede compra.',

    # Techniques 6-10
    'Techniques 6-10: Advanced Rapport Builders': 'T\u00e9cnicas 6-10: Constructores Avanzados de Rapport',
    '6. VULNERABILITY: Brief, genuine honesty creates deep trust. \'When I first started, I didn\'t believe the hype either. Then I tried it myself and became obsessed.\' This shows you\'re a real person, not a sales robot.': '6. VULNERABILIDAD: La honestidad breve y genuina crea confianza profunda. \'Cuando empec\u00e9, yo tampoco me cre\u00eda el hype. Luego lo prob\u00e9 yo misma y me obsesion\u00e9.\' Esto demuestra que eres una persona real, no un robot de ventas.',
    '7. CURIOSITY: Ask questions that show genuine interest in THEM, not just their wallet. \'What do you usually use on your skin? You clearly take care of yourself.\' People love talking about themselves.': '7. CURIOSIDAD: Haz preguntas que demuestren inter\u00e9s genuino en ELLOS, no solo en su billetera. \'\u00bfQu\u00e9 sueles usar en tu piel? Claramente te cuidas.\' A la gente le encanta hablar de s\u00ed misma.',
    '8. AGREEMENT FRAMES: Start with something they can\'t disagree with. \'Andorra is beautiful, isn\'t it?\' \'You clearly have great taste.\' \'Taking care of your skin is important.\' Each agreement creates momentum toward the sale.': '8. MARCOS DE ACUERDO: Empieza con algo con lo que no puedan estar en desacuerdo. \'Andorra es hermosa, \u00bfo no?\' \'Claramente tienes excelente gusto.\' \'Cuidar tu piel es importante.\' Cada acuerdo crea impulso hacia la venta.',
    '9. STORYTELLING: Share a 30-second story about another customer. \'A woman came in yesterday saying she\'d think about it. She came back an hour later and bought two for her sisters.\' Stories bypass skepticism and go straight to imagination.': '9. NARRACI\u00d3N: Comparte una historia de 30 segundos sobre otro cliente. \'Una mujer vino ayer diciendo que lo pensar\u00eda. Volvi\u00f3 una hora despu\u00e9s y compr\u00f3 dos para sus hermanas.\' Las historias evaden el escepticismo y van directo a la imaginaci\u00f3n.',
    '10. APPROPRIATE TOUCH: A light hand on the forearm during a key moment, or guiding their hand during the demo. Only when rapport is established and culturally appropriate. Touch accelerates trust when done right, destroys it when done wrong.': '10. TOQUE APROPIADO: Una mano ligera en el antebrazo durante un momento clave, o guiando su mano durante la demostraci\u00f3n. Solo cuando el rapport est\u00e1 establecido y es culturalmente apropiado. El toque acelera la confianza cuando se hace bien, la destruye cuando se hace mal.',
    'Rapport is not a script \u2014 it\'s a state of being. The most powerful rapport tool is genuine LIKING. Actually care about the person in front of you. Be curious about their life. When your interest is real, everything else falls into place.': 'El rapport no es un guion \u2014 es un estado de ser. La herramienta de rapport m\u00e1s poderosa es el genuino AGRADO. Realmente imp\u00f3rtate por la persona frente a ti. S\u00e9 curioso sobre su vida. Cuando tu inter\u00e9s es real, todo lo dem\u00e1s cae en su lugar.',

    # Quote
    'People don\'t care how much you know until they know how much you care. Rapport is the proof of caring.': 'La gente no le importa cu\u00e1nto sabes hasta que sabe cu\u00e1nto te importa. El rapport es la prueba de que te importa.',
    'Zero Lines Method': 'M\u00e9todo Zero Lines',

    # Quiz connect-5
    'What makes a compliment feel genuine rather than fake?': '\u00bfQu\u00e9 hace que un cumplido se sienta genuino en vez de falso?',
    'Using more elaborate words': 'Usar palabras m\u00e1s elaboradas',
    'Being specific about something the person chose': 'Ser espec\u00edfico sobre algo que la persona eligi\u00f3',
    'Complimenting their physical body': 'Cumplimentar su cuerpo f\u00edsico',
    'Complimenting them multiple times rapidly': 'Cumplimentarlos m\u00faltiples veces r\u00e1pidamente',
    'Specific compliments about choices people make (accessories, style, grooming) feel observant and real. Generic or physical compliments often feel fake or inappropriate.': 'Los cumplidos espec\u00edficos sobre las elecciones que hacen las personas (accesorios, estilo, aseo) se sienten observadores y reales. Los cumplidos gen\u00e9ricos o f\u00edsicos a menudo se sienten falsos o inapropiados.',
    'How should mirroring be done to avoid detection?': '\u00bfC\u00f3mo se debe hacer el espejo para evitar ser detectado?',
    'Copy their movements immediately and exactly': 'Copiar sus movimientos inmediata y exactamente',
    'Wait 2-3 seconds after they shift, then adjust your posture subtly': 'Esperar 2-3 segundos despu\u00e9s de que se muevan, y luego ajustar tu postura sutilmente',
    'Mirror only their speech, not body language': 'Hacer espejo solo de su habla, no del lenguaje corporal',
    'Tell them you\'re mirroring to build rapport': 'Decirles que est\u00e1s haciendo espejo para construir rapport',
    'Mirroring should be delayed by 2-3 seconds and done subtly. Immediate, exact copying feels like mimicry and backfires. Natural, delayed matching creates subconscious similarity.': 'El espejo debe retrasarse 2-3 segundos y hacerse sutilmente. La copia inmediata y exacta se siente como m\u00edmica y tiene efecto contrario. El emparejamiento natural y retrasado crea similitud subconsciente.',
    'Which type of humor is safest and most disarming in sales?': '\u00bfQu\u00e9 tipo de humor es el m\u00e1s seguro y desarmante en ventas?',
    'Political humor': 'Humor pol\u00edtico',
    'Self-deprecating humor': 'Humor autocr\u00edtico',
    'Sarcasm about the customer': 'Sarcasmo sobre el cliente',
    'Edgy jokes': 'Chistes atrevidos',
    'Self-deprecating humor is safest because it shows confidence and vulnerability without risking offense. Political, sarcastic, or edgy humor can alienate customers.': 'El humor autocr\u00edtico es el m\u00e1s seguro porque muestra confianza y vulnerabilidad sin arriesgarse a ofender. El humor pol\u00edtico, sarc\u00e1stico o atrevido puede alienar a los clientes.',

    # === LESSON connect-6: Asking Questions That Reveal Everything ===

    'Questions Are Your Intelligence-Gathering Tool': 'Las Preguntas Son Tu Herramienta de Recolecci\u00f3n de Inteligencia',
    'The salesperson who asks the best questions learns the most. And the salesperson who learns the most sells the most. Questions reveal spending power, skin concerns, buying motivation, decision dynamics, and objections \u2014 all before you present the offer. Master question-asking and you\'ll never be surprised by a \'no.\'': 'El vendedor que hace las mejores preguntas aprende m\u00e1s. Y el vendedor que m\u00e1s aprende, m\u00e1s vende. Las preguntas revelan poder adquisitivo, preocupaciones de la piel, motivaci\u00f3n de compra, din\u00e1micas de decisi\u00f3n y objeciones \u2014 todo antes de presentar la oferta. Domina el arte de preguntar y nunca te sorprender\u00e1 un \'no\'.',
    'Your goal with questions isn\'t interrogation \u2014 it\'s conversation. Questions should feel natural, flow with the chat, and make the customer feel understood, not interviewed.': 'Tu objetivo con las preguntas no es un interrogatorio \u2014 es conversaci\u00f3n. Las preguntas deben sentirse naturales, fluir con la charla, y hacer que el cliente se sienta entendido, no entrevistado.',

    # Open vs Closed Questions
    'Open vs. Closed Questions': 'Preguntas Abiertas vs. Cerradas',
    'Closed Questions (Weak)': 'Preguntas Cerradas (D\u00e9biles)',
    '\'Do you use cream?\' \u2014 Yes/No answer. Ends conversation. Reveals nothing. \'Do you like it?\' \u2014 \'It\'s nice.\' Dead end. \'Have you been to Andorra before?\' \u2014 \'Yes.\' Nothing to work with.': '\'\u00bfUsas crema?\' \u2014 Respuesta s\u00ed/no. Termina la conversaci\u00f3n. No revela nada. \'\u00bfTe gusta?\' \u2014 \'Est\u00e1 bonito.\' Callej\u00f3n sin salida. \'\u00bfHas estado en Andorra antes?\' \u2014 \'S\u00ed.\' Nada con qu\u00e9 trabajar.',
    'Open Questions (Powerful)': 'Preguntas Abiertas (Poderosas)',
    '\'What do you use on your skin?\' \u2014 Reveals routine, spending, and concerns. \'What do you think of the result?\' \u2014 Gets them talking about feelings. \'What brings you to Andorra?\' \u2014 Opens connection opportunities.': '\'\u00bfQu\u00e9 usas en tu piel?\' \u2014 Revela rutina, gasto y preocupaciones. \'\u00bfQu\u00e9 piensas del resultado?\' \u2014 Los hace hablar sobre sentimientos. \'\u00bfQu\u00e9 te trae a Andorra?\' \u2014 Abre oportunidades de conexi\u00f3n.',
    'Start with open questions. Use closed questions only to confirm what you\'ve learned (\'So you use a night cream already \u2014 that\'s great\'). Open questions gather intelligence; closed questions confirm understanding.': 'Empieza con preguntas abiertas. Usa preguntas cerradas solo para confirmar lo que has aprendido (\'As\u00ed que ya usas una crema de noche \u2014 eso es genial\'). Las preguntas abiertas recopilan inteligencia; las preguntas cerradas confirman entendimiento.',

    # The Question Ladder
    'The Question Ladder: From Surface to Deep': 'La Escalera de Preguntas: De Superficial a Profundo',
    'Don\'t start with personal questions. Build from light to deep, like climbing a ladder. Each level requires trust earned at the previous level.': 'No empieces con preguntas personales. Construye de ligero a profundo, como subir una escalera. Cada nivel requiere la confianza ganada en el nivel anterior.',
    'LEVEL 1 \u2014 OBSERVATIONAL (0-30 seconds): \'I love your scarf \u2014 is that from a local designer?\' \'How\'s your day in Andorra going?\' Light, surface-level, easy to answer. Creates initial comfort.': 'NIVEL 1 \u2014 OBSERVACIONAL (0-30 segundos): \'Me encanta tu bufanda \u2014 \u00bfes de un dise\u00f1ador local?\' \'\u00bfC\u00f3mo va tu d\u00eda en Andorra?\' Ligero, superficial, f\u00e1cil de responder. Crea comodidad inicial.',
    'LEVEL 2 \u2014 CONTEXTUAL (30 seconds - 2 minutes): \'What brings you to Andorra?\' \'Are you here for skiing or shopping?\' \'What do you usually use on your skin?\' Slightly more personal but still easy. Reveals context.': 'NIVEL 2 \u2014 CONTEXTUAL (30 segundos - 2 minutos): \'\u00bfQu\u00e9 te trae a Andorra?\' \'\u00bfEst\u00e1s aqu\u00ed para esquiar o de compras?\' \'\u00bfQu\u00e9 sueles usar en tu piel?\' Un poco m\u00e1s personal pero a\u00fan f\u00e1cil. Revela contexto.',
    'LEVEL 3 \u2014 PERSONAL (2-5 minutes): \'What are your main skin concerns?\' \'How much time do you spend on your skincare routine?\' \'When was the last time you really treated yourself?\' Requires some trust. Reveals motivation and concerns.': 'NIVEL 3 \u2014 PERSONAL (2-5 minutos): \'\u00bfCu\u00e1les son tus principales preocupaciones de piel?\' \'\u00bfCu\u00e1nto tiempo dedicas a tu rutina de cuidado de la piel?\' \'\u00bfCu\u00e1ndo fue la \u00faltima vez que realmente te consentiste?\' Requiere algo de confianza. Revela motivaci\u00f3n y preocupaciones.',
    'LEVEL 4 \u2014 DECISION-ORIENTED (During the close): \'Which option feels better for you?\' \'What would make this perfect for you?\' \'If price weren\'t an issue, which would you choose?\' Reveals objections and buying signals.': 'NIVEL 4 \u2014 ORIENTADO A LA DECISI\u00d3N (Durante el cierre): \'\u00bfCu\u00e1l opci\u00f3n se siente mejor para ti?\' \'\u00bfQu\u00e9 har\u00eda esto perfecto para ti?\' \'Si el precio no fuera un problema, \u00bfcu\u00e1l elegir\u00edas?\' Revela objeciones y se\u00f1ales de compra.',
    'Never skip levels. Asking a Level 3 question (\'What are your main skin concerns?\') before establishing any rapport feels invasive. Climb the ladder naturally.': 'Nunca te saltes niveles. Hacer una pregunta de Nivel 3 (\'\u00bfCu\u00e1les son tus principales preocupaciones de piel?\') antes de establecer cualquier rapport se siente invasivo. Sube la escalera naturalmente.',

    # Questions That Make Them Feel Smart
    'Questions That Make Them Feel Smart': 'Preguntas Que Los Hacen Sentir Inteligentes',
    'The best questions elevate the customer. They make the person feel knowledgeable, sophisticated, and perceptive. When someone feels smart, they\'re more confident \u2014 and confident buyers spend more.': 'Las mejores preguntas elevan al cliente. Hacen que la persona se sienta conocedora, sofisticada y perceptiva. Cuando alguien se siente inteligente, est\u00e1 m\u00e1s seguro \u2014 y los compradores seguros gastan m\u00e1s.',
    '\'You clearly take care of your skin \u2014 what products do you swear by?\' \u2014 Acknowledges their expertise while gathering data.': '\'Claramente cuidas tu piel \u2014 \u00bfen qu\u00e9 productos conf\u00edas?\' \u2014 Reconoce su experiencia mientras recopilas datos.',
    '\'I can tell you know quality \u2014 what do you look for in skincare?\' \u2014 Flatters their discernment.': '\'Se nota que conoces la calidad \u2014 \u00bfqu\u00e9 buscas en el cuidado de la piel?\' \u2014 Halaga su discernimiento.',
    '\'Most people don\'t know this, but the Dead Sea minerals are the most concentrated on Earth. Have you heard about them before?\' \u2014 Gives them a chance to show knowledge OR learn something impressive.': '\'La mayor\u00eda no lo sabe, pero los minerales del Mar Muerto son los m\u00e1s concentrados de la Tierra. \u00bfHab\u00edas escuchado sobre ellos?\' \u2014 Les da la oportunidad de demostrar conocimiento O aprender algo impresionante.',
    '\'You seem like someone who does their research. What have you heard about collagen treatments?\' \u2014 Positions them as informed and thoughtful.': '\'Pareces alguien que investiga. \u00bfQu\u00e9 has escuchado sobre los tratamientos de col\u00e1geno?\' \u2014 Los posiciona como informados y reflexivos.',

    # Questions to Uncover Objections Early
    'Questions to Uncover Objections Early': 'Preguntas Para Descubrir Objeciones a Tiempo',
    'If you know the objection before you present the offer, you can address it proactively. These questions reveal hidden concerns:': 'Si conoces la objeci\u00f3n antes de presentar la oferta, puedes abordarla proactivamente. Estas preguntas revelan preocupaciones ocultas:',
    '\'When you buy skincare, what matters most to you \u2014 ingredients, results, or value?\' \u2014 Reveals their buying criteria.': '\'Cuando compras productos de cuidado de la piel, \u00bfqu\u00e9 es lo m\u00e1s importante para ti \u2014 ingredientes, resultados o valor?\' \u2014 Revela sus criterios de compra.',
    '\'Are you shopping for yourself or looking for gifts too?\' \u2014 Reveals budget flexibility and motivation.': '\'\u00bfEst\u00e1s comprando para ti o tambi\u00e9n buscando regalos?\' \u2014 Revela flexibilidad de presupuesto y motivaci\u00f3n.',
    '\'What\'s your usual budget range for skincare treatments?\' \u2014 Direct but effective when asked warmly after rapport is built.': '\'\u00bfCu\u00e1l es tu rango de presupuesto habitual para tratamientos de cuidado de la piel?\' \u2014 Directo pero efectivo cuando se pregunta c\u00e1lidamente despu\u00e9s de haber construido rapport.',
    '\'Have you tried anything like this before? What was your experience?\' \u2014 Reveals past objections and expectations.': '\'\u00bfHas probado algo como esto antes? \u00bfCu\u00e1l fue tu experiencia?\' \u2014 Revela objeciones y expectativas pasadas.',

    # Avoiding Interrogation Mode
    'Avoiding Interrogation Mode': 'Evitando el Modo Interrogatorio',
    'Questions can backfire if they feel like an interview. Here\'s how to keep it conversational:': 'Las preguntas pueden tener efecto contrario si se sienten como una entrevista. Aqu\u00ed te decimos c\u00f3mo mantenerlo conversacional:',
    'SHARE BETWEEN QUESTIONS: Don\'t ask three questions in a row. Share something about yourself or the product between each question. It should feel like a conversation, not a survey.': 'COMPARTE ENTRE PREGUNTAS: No hagas tres preguntas seguidas. Comparte algo sobre ti o el producto entre cada pregunta. Debe sentirse como una conversaci\u00f3n, no una encuesta.',
    'USE STATEMENTS INSTEAD: Instead of \'Do you have dry skin?\' say \'The mountain air here can really dry out your skin.\' This invites them to respond without feeling questioned.': 'USA DECLARACIONES EN LUGAR DE PREGUNTAS: En vez de \'\u00bfTienes la piel seca?\' di \'El aire de monta\u00f1a aqu\u00ed puede resecar mucho la piel.\' Esto los invita a responder sin sentirse cuestionados.',
    'FOLLOW THE THREAD: When they mention something interesting, follow it. Don\'t rigidly stick to your question list. If they mention their daughter, ask about her. That\'s where the real connection lives.': 'SIGUE EL HILO: Cuando mencionen algo interesante, s\u00edguelo. No te aferres r\u00edgido a tu lista de preguntas. Si mencionan a su hija, pregunta por ella. Ah\u00ed es donde vive la conexi\u00f3n real.',
    'KEEP IT LIGHT: Heavy, serious questioning creates pressure. Maintain a warm, playful tone throughout.': 'M\u00c1NTENLO LIGERO: Un cuestionamiento pesado y serio crea presi\u00f3n. Mant\u00e9n un tono c\u00e1lido y juguet\u00f3n durante todo el proceso.',
    '\'So what brings you to Andorra?\' \u2014 \'Skiing with my husband.\' \u2014 \'Oh amazing! Which ski resort? I love the slopes here. And after a day of skiing, your skin must be so dry \u2014 the mountain air is brutal. What do you usually use to rehydrate?\' See how each question follows naturally from the last? That\'s conversational questioning.': '\'Entonces, \u00bfqu\u00e9 te trae a Andorra?\' \u2014 \'A esquiar con mi esposo.\' \u2014 \'\u00a1Oh, incre\u00edble! \u00bfQu\u00e9 estaci\u00f3n de esqu\u00ed? Me encantan las pistas aqu\u00ed. Y despu\u00e9s de un d\u00eda de esqu\u00ed, tu piel debe estar bien reseca \u2014 el aire de monta\u00f1a es brutal. \u00bfQu\u00e9 sueles usar para rehidratar?\' \u00bfVes c\u00f3mo cada pregunta sigue naturalmente de la anterior? Eso es cuestionar de forma conversacional.',
    'The best salespeople don\'t talk customers into buying. They ask customers into revealing what they truly want. Then they simply provide it.': 'Los mejores vendedores no convencen a los clientes para que compren. Le preguntan a los clientes hasta revelar lo que realmente quieren. Y luego simplemente se lo proporcionan.',

    # Quiz connect-6
    'What is the main difference between open and closed questions?': '\u00bfCu\u00e1l es la diferencia principal entre preguntas abiertas y cerradas?',
    'Open questions are longer': 'Las preguntas abiertas son m\u00e1s largas',
    'Open questions invite detailed responses and reveal information; closed questions get yes/no answers': 'Las preguntas abiertas invitan respuestas detalladas y revelan informaci\u00f3n; las preguntas cerradas obtienen respuestas s\u00ed/no',
    'Closed questions are more polite': 'Las preguntas cerradas son m\u00e1s educadas',
    'Open questions are only for experienced sellers': 'Las preguntas abiertas son solo para vendedores experimentados',
    'Open questions (What, How, Why) invite detailed responses that reveal information. Closed questions (Do, Are, Have) get yes/no answers that end conversation.': 'Las preguntas abiertas (Qu\u00e9, C\u00f3mo, Por qu\u00e9) invitan respuestas detalladas que revelan informaci\u00f3n. Las preguntas cerradas (Haces, Est\u00e1s, Has) obtienen respuestas s\u00ed/no que terminan la conversaci\u00f3n.',
    'What does the \'question ladder\' refer to?': '\u00bfA qu\u00e9 se refiere la \'escalera de preguntas\'?',
    'Asking as many questions as possible': 'Hacer tantas preguntas como sea posible',
    'Building from light surface questions to deeper personal ones as trust develops': 'Construir de preguntas superficiales ligeras a preguntas personales m\u00e1s profundas a medida que se desarrolla la confianza',
    'Only asking questions about the product': 'Solo hacer preguntas sobre el producto',
    'A specific list of 10 questions every seller must ask': 'Una lista espec\u00edfica de 10 preguntas que todo vendedor debe hacer',
    'The question ladder means starting with light observational questions, then moving to contextual, personal, and finally decision-oriented questions as trust builds. Skipping levels feels invasive.': 'La escalera de preguntas significa empezar con preguntas observacionales ligeras, luego pasar a contextuales, personales y finalmente orientadas a la decisi\u00f3n a medida que se construye la confianza. Saltarse niveles se siente invasivo.',
    'How can you avoid \'interrogation mode\' when asking questions?': '\u00bfC\u00f3mo puedes evitar el \'modo interrogatorio\' al hacer preguntas?',
    'Only ask one question per interaction': 'Solo hacer una pregunta por interacci\u00f3n',
    'Share information between questions and follow conversational threads naturally': 'Compartir informaci\u00f3n entre preguntas y seguir los hilos conversacionales naturalmente',
    'Write all questions down and read them': 'Escribir todas las preguntas y leerlas',
    'Avoid questions altogether': 'Evitar las preguntas por completo',
    'Avoid interrogation by sharing between questions, following conversational threads (not rigid lists), using statements that invite response, and keeping the tone light and warm.': 'Evita el interrogatorio compartiendo entre preguntas, siguiendo hilos conversacionales (no listas r\u00edgidas), usando declaraciones que invitan a responder, y manteniendo el tono ligero y c\u00e1lido.',

    # === LESSON connect-7: Spotting Buying Signals ===

    'The Customer Is Always Telling You What They Want \u2014 If You\'re Listening': 'El Cliente Siempre Te Est\u00e1 Diciendo Lo Que Quiere \u2014 Si Est\u00e1s Escuchando',
    'The biggest mistake in sales is talking past the buying signal. The customer leans in, touches the product, asks about price \u2014 and the salesperson keeps pitching instead of closing. Buying signals are the green lights of sales. They tell you the customer is ready. Your job is to see them and act.': 'El error m\u00e1s grande en ventas es seguir hablando despu\u00e9s de la se\u00f1al de compra. El cliente se inclina, toca el producto, pregunta por el precio \u2014 y el vendedor sigue presentando en vez de cerrar. Las se\u00f1ales de compra son las luces verdes de las ventas. Te dicen que el cliente est\u00e1 listo. Tu trabajo es verlas y actuar.',
    'Buying signals happen before the customer verbally commits. If you wait for them to say \'I\'ll take it,\' you\'ve waited too long. Close when you SEE the signal, not when you HEAR the decision.': 'Las se\u00f1ales de compra suceden antes de que el cliente se comprometa verbalmente. Si esperas a que digan \'Me lo llevo\', has esperado demasiado. Cierra cuando VEAS la se\u00f1al, no cuando ESCUCHES la decisi\u00f3n.',

    # Physical Buying Signals
    'Physical Buying Signals': 'Se\u00f1ales de Compra F\u00edsicas',
    'The body reveals the decision before the mouth does. Watch for these physical cues:': 'El cuerpo revela la decisi\u00f3n antes que la boca. Estate atento a estas se\u00f1ales f\u00edsicas:',
    'LEANING IN: When a customer physically moves closer to you, the product, or the mirror, they\'re interested. Leaning back or stepping away means resistance. Leaning in means engagement.': 'INCLINARSE HACIA ADELANTE: Cuando un cliente se acerca f\u00edsicamente a ti, al producto o al espejo, est\u00e1 interesado. Inclinarse hacia atr\u00e1s o alejarse significa resistencia. Inclinarse hacia adelante significa compromiso.',
    'TOUCHING THE FACE: Touching cheeks, chin, or under the eyes while looking at the product or mirror = they\'re imagining themselves using it. This is one of the strongest positive signals.': 'TOCARSE LA CARA: Tocarse las mejillas, la barbilla o debajo de los ojos mientras miran el producto o el espejo = se est\u00e1n imaginando us\u00e1ndolo. Esta es una de las se\u00f1ales positivas m\u00e1s fuertes.',
    'HOLDING THE PRODUCT: If they pick up the bottle, read the label, or turn it over in their hands, they\'re taking ownership mentally. Encourage this \u2014 let them hold it.': 'SOSTENER EL PRODUCTO: Si toman el frasco, leen la etiqueta o lo giran en sus manos, se est\u00e1n apropiando mentalmente. Anima esto \u2014 d\u00e9jalos sostenerlo.',
    'MIRROR CHECKING: Looking at themselves in the mirror repeatedly during or after the demo is a strong buying signal. They like what they see and are imagining the result.': 'REVISARSE EN EL ESPEJO: Mirarse en el espejo repetidamente durante o despu\u00e9s de la demostraci\u00f3n es una fuerte se\u00f1al de compra. Les gusta lo que ven y se est\u00e1n imaginando el resultado.',
    'RELAXED SHOULDERS: Tense shoulders signal hesitation. When shoulders drop and relax, resistance is dropping too.': 'HOMBROS RELAJADOS: Hombros tensos se\u00f1alan duda. Cuando los hombros bajan y se relajan, la resistencia tambi\u00e9n disminuye.',
    'OPEN PALMS: Showing open palms while discussing the product indicates openness and receptivity. Closed fists or crossed arms signal the opposite.': 'PALMAS ABIERTAS: Mostrar las palmas abiertas mientras discuten el producto indica apertura y receptividad. Pu\u00f1os cerrados o brazos cruzados se\u00f1alan lo opuesto.',
    'NODDING: Nodding while you speak (especially during the offer) indicates agreement. Multiple nods = building commitment.': 'ASENTIR: Asentir mientras hablas (especialmente durante la oferta) indica acuerdo. M\u00faltiples asentimientos = construyendo compromiso.',

    # Verbal Buying Signals
    'Verbal Buying Signals': 'Se\u00f1ales de Compra Verbales',
    'Words are data. These phrases almost always indicate buying intent:': 'Las palabras son datos. Estas frases casi siempre indican intenci\u00f3n de compra:',
    '\'HOW LONG DOES IT LAST?\' \u2014 They\'re calculating value per use. This is a value-oriented buyer calculating ROI.': '\'\u00bfCU\u00c1NTO DURA?\' \u2014 Est\u00e1n calculando el valor por uso. Este es un comprador orientado al valor calculando el ROI.',
    '\'DO YOU SHIP?\' \u2014 They\'re imagining owning it but worried about logistics. Solve the logistics, close the sale.': '\'\u00bfHACEN ENV\u00cdOS?\' \u2014 Se est\u00e1n imaginando teni\u00e9ndolo pero preocupados por la log\u00edstica. Resuelve la log\u00edstica, cierra la venta.',
    '\'HOW OFTEN DO I USE IT?\' \u2014 They\'re fitting it into their lifestyle. Mental ownership has begun.': '\'\u00bfCON QU\u00c9 FRECUENCIA LO USO?\' \u2014 Lo est\u00e1n integrando a su estilo de vida. La apropiaci\u00f3n mental ha comenzado.',
    '\'WHAT DO YOU THINK?\' (to partner) \u2014 They\'re seeking validation for a decision they\'ve already made. Engage the partner positively.': '\'\u00bfT\u00da QU\u00c9 PIENSAS?\' (a su pareja) \u2014 Buscan validaci\u00f3n para una decisi\u00f3n que ya tomaron. Involucra a la pareja positivamente.',
    '\'CAN I GET THIS IN...?\' \u2014 They\'re personalizing the purchase. Color, size, scent \u2014 doesn\'t matter. Personalization = commitment.': '\'\u00bfPUEDO LLEVAR ESTO EN...?\' \u2014 Est\u00e1n personalizando la compra. Color, tama\u00f1o, aroma \u2014 no importa. Personalizaci\u00f3n = compromiso.',
    '\'IS THIS THE LAST ONE?\' \u2014 Scarcity concern means they want it. Create gentle urgency.': '\'\u00bfESTE ES EL \u00daLTIMO?\' \u2014 La preocupaci\u00f3n por escasez significa que lo quieren. Crea urgencia sutil.',
    '\'WHAT\'S THE RETURN POLICY?\' \u2014 Risk management. They\'re close but need a safety net.': '\'\u00bfCU\u00c1L ES LA POL\u00cdTICA DE DEVOLUCI\u00d3N?\' \u2014 Gesti\u00f3n de riesgo. Est\u00e1n cerca pero necesitan una red de seguridad.',
    '\'DO YOU HAVE A CARD?\' \u2014 This is as close to \'I\'ll take it\' as you can get without hearing the words. Close immediately.': '\'\u00bfTIENES TARJETA?\' \u2014 Esto es tan cerca de \'Me lo llevo\' como puedes estar sin escuchar las palabras. Cierra inmediatamente.',

    # Micro-Signals
    'The Micro-Signals: Blink-and-You-Miss-Them': 'Las Micro-Se\u00f1ales: Parpadeas y Te las Pierdes',
    'These happen in fractions of a second. Train yourself to notice:': 'Estas suceden en fracciones de segundo. Entr\u00e9nate para notarlas:',
    'EYEBROW FLASH: A quick raise of both eyebrows when you mention a benefit or show the result. Surprise and interest. Follow up immediately.': 'DESTELLO DE CEJAS: Un levantamiento r\u00e1pido de ambas cejas cuando mencionas un beneficio o muestras el resultado. Sorpresa e inter\u00e9s. Da seguimiento inmediatamente.',
    'PUPIL DILATION: When people see something they want, their pupils dilate. Hard to spot but reliable.': 'DILATACI\u00d3N PUPILAR: Cuando la gente ve algo que quiere, sus pupilas se dilatan. Dif\u00edcil de notar pero confiable.',
    'LIP PRESS: Pressing lips together while considering = internal deliberation. Stay quiet and let them think.': 'PRESI\u00d3N DE LABIOS: Presionar los labios juntos mientras consideran = deliberaci\u00f3n interna. Mantente callado y d\u00e9jalos pensar.',
    'BREATH HOLD + RELEASE: Holding breath during the price reveal, then releasing = relief. They can afford it.': 'AGUANTAR LA RESPIRACI\u00d3N + SOLTAR: Aguantar la respiraci\u00f3n durante la revelaci\u00f3n del precio, y luego soltar = alivio. Pueden pagarlo.',
    'QUICK GLANCE AT WALLET/BAG: Checking if they have payment ready. Almost always a buying signal.': 'MIRADA R\u00c1PIDA A LA CARTERA/BOLSA: Verificando si tienen el pago listo. Casi siempre es una se\u00f1al de compra.',

    # When to Close
    'When to Close: Timing Is Everything': 'Cu\u00e1ndo Cerrar: El Momento Lo Es Todo',
    'Closing too early feels pushy. Closing too late loses momentum. The sweet spot is the SECOND buying signal. Here\'s why:': 'Cerrar demasiado temprano se siente agresivo. Cerrar demasiado tarde pierde el impulso. El punto ideal es la SEGUNDA se\u00f1al de compra. Aqu\u00ed te explicamos por qu\u00e9:',
    'FIRST SIGNAL: \'Interesting.\' They lean in. Good, but not enough. Keep building value.': 'PRIMERA SE\u00d1AL: \'Interesante.\' Se inclinan. Bueno, pero no suficiente. Sigue construyendo valor.',
    'SECOND SIGNAL: They touch the product and ask \'How long does it last?\' NOW. This is your moment. The second signal confirms genuine interest, not just politeness.': 'SEGUNDA SE\u00d1AL: Tocan el producto y preguntan \'\u00bfCu\u00e1nto dura?\' AHORA. Este es tu momento. La segunda se\u00f1al confirma inter\u00e9s genuino, no solo cortes\u00eda.',
    'THIRD SIGNAL: They\'re asking about payment or shipping. If you haven\'t closed by now, close immediately \u2014 every word past this point risks the sale.': 'TERCERA SE\u00d1AL: Est\u00e1n preguntando sobre pago o env\u00edo. Si no has cerrado para ahora, cierra inmediatamente \u2014 cada palabra despu\u00e9s de este punto arriesga la venta.',
    'Customer: \'How long does one syringe last?\' (Buying signal!) You: \'A full year of treatments \u2014 52 weeks. That\'s less than \u20ac6 per week for this result. Shall I set one aside for you?\' Direct close. Don\'t oversell past this point.': 'Cliente: \'\u00bfCu\u00e1nto dura una jeringa?\' (\u00a1Se\u00f1al de compra!) T\u00fa: \'Un a\u00f1o completo de tratamientos \u2014 52 semanas. Eso es menos de \u20ac6 por semana por este resultado. \u00bfTe guardo una?\' Cierre directo. No vendas de m\u00e1s despu\u00e9s de este punto.',
    'When you spot a buying signal, STOP TALKING ABOUT FEATURES. Switch to closing mode. Summarize the value, present the options, and ask for the decision. Every additional feature you mention past the buying signal creates new objections.': 'Cuando detectes una se\u00f1al de compra, DEJA DE HABLAR SOBRE CARACTER\u00cdSTICAS. Cambia al modo de cierre. Resume el valor, presenta las opciones, y pide la decisi\u00f3n. Cada caracter\u00edstica adicional que menciones despu\u00e9s de la se\u00f1al de compra crea nuevas objeciones.',

    # False Signals
    'False Signals: When Interest Isn\'t Buying Intent': 'Se\u00f1ales Falsas: Cuando el Inter\u00e9s No es Intenci\u00f3n de Compra',
    'Not every positive signal means a sale is imminent. Learn to distinguish genuine buying signals from polite interest:': 'No toda se\u00f1al positiva significa que una venta es inminente. Aprende a distinguir las se\u00f1ales de compra genuinas del inter\u00e9s cort\u00e9s:',
    'Genuine Buying Signal': 'Se\u00f1al de Compra Genuina',
    'They ask specific questions about usage, logistics, or value. Their questions are about OWNING the product. They\'re problem-solving for purchase.': 'Hacen preguntas espec\u00edficas sobre uso, log\u00edstica o valor. Sus preguntas son sobre POSEER el producto. Est\u00e1n resolviendo problemas para la compra.',
    'Polite Interest (Not Ready)': 'Inter\u00e9s Cort\u00e9s (No Est\u00e1 Listo)',
    'They say \'It\'s nice\' or \'I\'ll think about it.\' Their questions are general. No specifics about owning. They\'re being polite, not buying.': 'Dicen \'Est\u00e1 bonito\' o \'Lo voy a pensar.\' Sus preguntas son generales. No hay especificidades sobre poseer. Est\u00e1n siendo corteses, no comprando.',
    'The moment you see the buying signal, your job changes from convincing to facilitating. Make it easy for them to say yes.': 'En el momento en que ves la se\u00f1al de compra, tu trabajo cambia de convencer a facilitar. Haz que sea f\u00e1cil para ellos decir s\u00ed.',

    # Quiz connect-7
    'When is the optimal time to close based on buying signals?': '\u00bfCu\u00e1ndo es el momento \u00f3ptimo para cerrar bas\u00e1ndose en las se\u00f1ales de compra?',
    'After the first positive signal': 'Despu\u00e9s de la primera se\u00f1al positiva',
    'After the second buying signal confirms genuine interest': 'Despu\u00e9s de que la segunda se\u00f1al de compra confirma inter\u00e9s genuino',
    'Only after they explicitly say they want to buy': 'Solo despu\u00e9s de que digan expl\u00edcitamente que quieren comprar',
    'After you\'ve listed all product features': 'Despu\u00e9s de haber listado todas las caracter\u00edsticas del producto',
    'The second buying signal is the sweet spot. The first signal could be politeness; the second confirms genuine interest. Closing after the third signal may be too late.': 'La segunda se\u00f1al de compra es el punto ideal. La primera se\u00f1al podr\u00eda ser cortes\u00eda; la segunda confirma inter\u00e9s genuino. Cerrar despu\u00e9s de la tercera se\u00f1al puede ser demasiado tarde.',
    'Which of these is a strong PHYSICAL buying signal?': '\u00bfCu\u00e1l de estas es una fuerte se\u00f1al de compra F\u00cdSICA?',
    'Checking their phone': 'Revisar su tel\u00e9fono',
    'Touching their face while looking at the product': 'Tocarse la cara mientras miran el producto',
    'Crossing their arms': 'Cruzar los brazos',
    'Stepping backward': 'Dar un paso hacia atr\u00e1s',
    'Touching the face (cheeks, chin, under eyes) while looking at the product means they\'re imagining themselves using it. This is one of the strongest positive buying signals.': 'Tocarse la cara (mejillas, barbilla, debajo de los ojos) mientras miran el producto significa que se est\u00e1n imaginando us\u00e1ndolo. Esta es una de las se\u00f1ales de compra positivas m\u00e1s fuertes.',
    'What should you do when you spot a buying signal?': '\u00bfQu\u00e9 debes hacer cuando detectas una se\u00f1al de compra?',
    'Keep listing more product features': 'Seguir listando m\u00e1s caracter\u00edsticas del producto',
    'Switch to closing mode and stop adding new information': 'Cambiar al modo de cierre y dejar de agregar nueva informaci\u00f3n',
    'Lower the price immediately': 'Bajar el precio inmediatamente',
    'Ask if they\'re ready to buy in a pushy way': 'Preguntar si est\u00e1n listos para comprar de forma agresiva',
    'When you spot a buying signal, switch from convincing to closing. Summarize value, present options, and ask for the decision. Every new feature you mention creates potential objections.': 'Cuando detectas una se\u00f1al de compra, cambia de convencer a cerrar. Resume el valor, presenta las opciones, y pide la decisi\u00f3n. Cada nueva caracter\u00edstica que mencionas crea objeciones potenciales.',

    # === LESSON connect-8: Handling Different Personality Types ===

    'One Pitch Does NOT Fit All': 'Una Presentaci\u00f3n No Le Queda a Todos',
    'You\'ve probably noticed that some customers want every detail while others just want the bottom line. Some need to feel emotionally connected; others want facts and data. These differences aren\'t random \u2014 they\'re personality types. Understanding the four buyer types transforms your approach from guessing to precision.': 'Probablemente has notado que algunos clientes quieren cada detalle mientras que otros solo quieren ir al grano. Algunos necesitan sentirse emocionalmente conectados; otros quieren hechos y datos. Estas diferencias no son al azar \u2014 son tipos de personalidad. Entender los cuatro tipos de comprador transforma tu enfoque de adivinar a precisi\u00f3n.',
    'The four buyer types \u2014 Analytical, Driver, Amiable, and Expressive \u2014 each require a different sales approach. Using the wrong style with the wrong type is like speaking French to a German speaker. Adapt and close.': 'Los cuatro tipos de comprador \u2014 Anal\u00edtico, Conductor, Amable y Expresivo \u2014 cada uno requiere un enfoque de venta diferente. Usar el estilo equivocado con el tipo equivocado es como hablarle en franc\u00e9s a un alem\u00e1n. Ad\u00e1ptate y cierra.',

    # Type 1: The Analytical
    'Type 1: The Analytical (Facts First)': 'Tipo 1: El Anal\u00edtico (Hechos Primero)',
    'The Analytical buyer is methodical, detail-oriented, and risk-averse. They want to understand HOW the product works before they commit. They\'ll ask about ingredients, research, and proof. They\'re not being difficult \u2014 they\'re being thorough.': 'El comprador Anal\u00edtico es met\u00f3dico, orientado a los detalles y adverso al riesgo. Quiere entender C\u00d3MO funciona el producto antes de comprometerse. Preguntar\u00e1 sobre ingredientes, investigaci\u00f3n y pruebas. No est\u00e1 siendo dif\u00edcil \u2014 est\u00e1 siendo minucioso.',
    'IDENTIFYING THEM: Asks specific questions about ingredients, science, or proof. Reads labels. Takes time to consider. May seem skeptical but is actually just processing.': 'IDENTIFICARLOS: Preguntan cosas espec\u00edficas sobre ingredientes, ciencia o pruebas. Leen etiquetas. Toman tiempo para considerar. Pueden parecer esc\u00e9pticos pero en realidad solo est\u00e1n procesando.',
    'YOUR APPROACH: Lead with facts and evidence. \'This is recommended by dermatologists.\' \'The Dead Sea has the highest mineral concentration on Earth.\' \'One syringe lasts 52 treatments \u2014 here is the math.\'': 'TU ENFOQUE: Empieza con hechos y evidencia. \'Esto es recomendado por dermat\u00f3logos.\' \'El Mar Muerto tiene la mayor concentraci\u00f3n de minerales de la Tierra.\' \'Una jeringa dura 52 tratamientos \u2014 aqu\u00ed est\u00e1 la cuenta.\'',
    'WHAT TO AVOID: High-pressure tactics, emotional appeals, rushing them. They need time. Pressure creates resistance, not commitment.': 'QU\u00c9 EVITAR: T\u00e1cticas de alta presi\u00f3n, apelaciones emocionales, apurarlos. Necesitan tiempo. La presi\u00f3n crea resistencia, no compromiso.',
    'CLOSING TECHNIQUE: Give them space to decide. \'I know you want to think this through. Here is my WhatsApp \u2014 if you have any questions later, just ask.\' Respect their process.': 'T\u00c9CNICA DE CIERRE: D\u00e9les espacio para decidir. \'S\u00e9 que quieres pensarlo bien. Aqu\u00ed est\u00e1 mi WhatsApp \u2014 si tienes alguna pregunta despu\u00e9s, solo escr\u00edbeme.\' Respeta su proceso.',
    '\'I completely understand wanting the details. The active ingredient is Dead Sea mineral salt, which contains 21 minerals including magnesium, calcium, and potassium. These are clinically shown to improve skin barrier function. One jar gives you 8-12 months of weekly treatments. The math works out to about \u20ac2 per use. Does that help with your decision?\' Facts, structure, respect.': '\'Entiendo perfectamente que quieras los detalles. El ingrediente activo es sal mineral del Mar Muerto, que contiene 21 minerales incluyendo magnesio, calcio y potasio. Estos han demostrado cl\u00ednicamente mejorar la funci\u00f3n de barrera de la piel. Un frasco te da 8-12 meses de tratamientos semanales. La cuenta sale a unos \u20ac2 por uso. \u00bfEso te ayuda con tu decisi\u00f3n?\' Hechos, estructura, respeto.',

    # Type 2: The Driver
    'Type 2: The Driver (Results Fast)': 'Tipo 2: El Conductor (Resultados R\u00e1pidos)',
    'The Driver is goal-oriented, time-pressed, and decisive. They don\'t want small talk. They want to know what it does, what it costs, and whether it works. Waste their time and they are gone.': 'El Conductor est\u00e1 orientado a objetivos, con poco tiempo, y es decisivo. No quiere pl\u00e1tica ligera. Quiere saber qu\u00e9 hace, cu\u00e1nto cuesta, y si funciona. Pierdes su tiempo y se van.',
    'IDENTIFYING THEM: Walks with purpose. Checks their watch. Gives direct answers. May seem abrupt \u2014 they are not rude, they are efficient.': 'IDENTIFICARLOS: Caminan con prop\u00f3sito. Revisan su reloj. Dan respuestas directas. Pueden parecer abruptos \u2014 no son groseros, son eficientes.',
    'YOUR APPROACH: Fast, direct, results-focused. Skip the long rapport-building. Get to the demo and the result quickly. \'Two minutes, visible result, lasts a year.\'': 'TU ENFOQUE: R\u00e1pido, directo, enfocado en resultados. Omite la larga construcci\u00f3n de rapport. Ve a la demostraci\u00f3n y al resultado r\u00e1pido. \'Dos minutos, resultado visible, dura un a\u00f1o.\'',
    'WHAT TO AVOID: Excessive chatting, too many options, slow pacing. Drivers want to make a decision and move on. Respect their time.': 'QU\u00c9 EVITAR: Pl\u00e1tica excesiva, demasiadas opciones, ritmo lento. Los Conductores quieren tomar una decisi\u00f3n y seguir adelante. Respeta su tiempo.',
    'CLOSING TECHNIQUE: Binary choice, quick close. \'Option 1: \u20ac210 with a gift. Option 2: \u20ac300 with two syringes. Which works for you?\' Clean and decisive.': 'T\u00c9CNICA DE CIERRE: Elecci\u00f3n binaria, cierre r\u00e1pido. \'Opci\u00f3n 1: \u20ac210 con regalo. Opci\u00f3n 2: \u20ac300 con dos jeringas. \u00bfCu\u00e1l te funciona?\' Limpio y decisivo.',
    '\'I know you are in a hurry. Two minutes. One eye. You will see the result yourself in the mirror. If you don\'t love it, no problem. If you do, I have two price options that take 30 seconds to explain. Sound fair?\' Direct, time-bound, respectful of their schedule.': '\'S\u00e9 que tienes prisa. Dos minutos. Un ojo. Ver\u00e1s el resultado t\u00fa misma en el espejo. Si no te encanta, no hay problema. Si s\u00ed, tengo dos opciones de precio que toman 30 segundos en explicar. \u00bfTe parece justo?\' Directo, con tiempo definido, respetuoso de su agenda.',

    # Type 3: The Amiable
    'Type 3: The Amiable (Feel Good)': 'Tipo 3: El Amable (Se Siente Bien)',
    'The Amiable buyer is warm, people-oriented, and relationship-driven. They want to trust you before they buy from you. They make decisions based on how the purchase FEELS, not just the product specs.': 'El comprador Amable es c\u00e1lido, orientado a las personas e impulsado por las relaciones. Quiere confiar en ti antes de comprarte. Toman decisiones bas\u00e1ndose en c\u00f3mo se SIENTE la compra, no solo en las especificaciones del producto.',
    'IDENTIFYING THEM: Friendly, asks personal questions, engages in chat, makes eye contact, smiles easily. Takes their partner\'s opinion seriously. Often the most fun to work with.': 'IDENTIFICARLOS: Amigables, hacen preguntas personales, se involucran en la pl\u00e1tica, hacen contacto visual, sonr\u00eden f\u00e1cilmente. Toman en serio la opini\u00f3n de su pareja. A menudo los m\u00e1s divertidos de atender.',
    'YOUR APPROACH: Build genuine rapport first. Share stories. Make them feel special. Emotional connection is the gateway to the sale. The demo should feel like an experience, not a transaction.': 'TU ENFOQUE: Construye rapport genuino primero. Comparte historias. Haz que se sientan especiales. La conexi\u00f3n emocional es la puerta de entrada a la venta. La demostraci\u00f3n debe sentirse como una experiencia, no una transacci\u00f3n.',
    'WHAT TO AVOID: Cold facts, aggressive closing, making them feel rushed. Amiable buyers need warmth and connection. Pressure feels like betrayal.': 'QU\u00c9 EVITAR: Hechos fr\u00edos, cierre agresivo, hacer que se sientan apurados. Los compradores Amables necesitan calidez y conexi\u00f3n. La presi\u00f3n se siente como traici\u00f3n.',
    'CLOSING TECHNIQUE: Emotional framing with partner involvement. \'Imagine waking up every morning looking this fresh. Which option feels right for you?\' Feelings over facts.': 'T\u00c9CNICA DE CIERRE: Enmarcado emocional con involucramiento de la pareja. \'Imagina despertar cada ma\u00f1ana vi\u00e9ndote as\u00ed de fresca. \u00bfCu\u00e1l opci\u00f3n se siente bien para ti?\' Sentimientos sobre hechos.',
    '\'Oh my gosh, your energy is amazing! Where are you visiting from? ... That is incredible! I love it there. You know what, I am going to give you my favorite treatment \u2014 it is like a spa moment in the middle of your shopping day. Just relax and enjoy.\' Experience-first, relationship-driven, warm.': '\'\u00a1Dios m\u00edo, tu energ\u00eda es incre\u00edble! \u00bfDe d\u00f3nde nos visitas? ... \u00a1Eso es incre\u00edble! Me encanta ah\u00ed. \u00a1Sabes qu\u00e9? Te voy a dar mi tratamiento favorito \u2014 es como un momento de spa en medio de tu d\u00eda de compras. Solo rel\u00e1jate y disfruta.\' Experiencia primero, relaci\u00f3n como motor, c\u00e1lido.',

    # Type 4: The Expressive
    'Type 4: The Expressive (Storyteller)': 'Tipo 4: El Expresivo (El Narrador)',
    'The Expressive buyer is enthusiastic, talkative, and imaginative. They love stories, emotions, and the big picture. They may seem scattered because they jump between topics \u2014 that is just how their mind works.': 'El comprador Expresivo es entusiasta, hablador e imaginativo. Aman las historias, las emociones y la visi\u00f3n general. Pueden parecer dispersos porque saltan entre temas \u2014 as\u00ed es como funciona su mente.',
    'IDENTIFYING THEM: Talks a lot, tells stories, gets excited easily, asks creative questions, imagines scenarios (\'Oh, my sister would LOVE this!\').': 'IDENTIFICARLOS: Hablan mucho, cuentan historias, se emocionan f\u00e1cilmente, hacen preguntas creativas, imaginan escenarios (\'\u00a1Oh, a mi hermana le ENCANTAR\u00cdA esto!\').',
    'YOUR APPROACH: Match their enthusiasm. Use storytelling. Paint pictures of the future. \'Your skin will glow like you just came back from a two-week spa retreat.\' Let them talk \u2014 they sell themselves through their own excitement.': 'TU ENFOQUE: Empareja su entusiasmo. Usa narraci\u00f3n. Pinta cuadros del futuro. \'Tu piel va a brillar como si acabaras de regresar de un retiro de spa de dos semanas.\' D\u00e9jalos hablar \u2014 se venden a s\u00ed mismos a trav\u00e9s de su propia emoci\u00f3n.',
    'WHAT TO AVOID: Shutting down their stories, being too structured, dampening their enthusiasm. Expressive buyers need to feel heard and excited.': 'QU\u00c9 EVITAR: Cortarles sus historias, ser demasiado estructurado, apagar su entusiasmo. Los compradores Expresivos necesitan sentirse escuchados y emocionados.',
    'CLOSING TECHNIQUE: Story-based close with gift potential. \'Your sister would absolutely love this too! Should we do two \u2014 one for you, one for her?\' Connect their enthusiasm to the purchase.': 'T\u00c9CNICA DE CIERRE: Cierre basado en historias con potencial de regalo. \'\u00a1Tu hermana tambi\u00e9n amar\u00eda esto! \u00bfHacemos dos \u2014 uno para ti, uno para ella?\' Conecta su entusiasmo con la compra.',
    '\'Wait until you tell your friends about this! They are going to be SO jealous. You will be at brunch like \'Oh this? Just something I picked up in Andorra.\' So \u2014 are we doing the full experience or starting with the essentials? Let us make it fun!\' Enthusiastic, story-driven, playful.': '\'\u00a1Espera a que les cuentes a tus amigas sobre esto! Van a estar TAN celosas. Vas a estar en el brunch como \'\u00bfOh, esto? Algo que compr\u00e9 en Andorra.\' Entonces \u2014 \u00bfhacemos la experiencia completa o empezamos con lo esencial? \u00a1Hag\u00e1moslo divertido!\' Entusiasta, impulsado por historias, juguet\u00f3n.',

    # Quick Reference
    'Quick Reference: Adapting Your Style': 'Referencia R\u00e1pida: Adaptando Tu Estilo',
    'ANALYTICAL \u2192 Use data, respect their process, give space': 'ANAL\u00cdTICO \u2192 Usa datos, respeta su proceso, d\u00e9 espacio',
    'DRIVER \u2192 Be fast, be direct, respect their time': 'CONDUCTOR \u2192 S\u00e9 r\u00e1pido, s\u00e9 directo, respeta su tiempo',
    'AMIABLE \u2192 Build rapport, create warmth, involve feelings': 'AMABLE \u2192 Construye rapport, crea calidez, involucra sentimientos',
    'EXPRESSIVE \u2192 Match enthusiasm, tell stories, paint pictures': 'EXPRESIVO \u2192 Empareja entusiasmo, cuenta historias, pinta cuadros',
    'Most people are a blend of two types. A Driver-Analytical wants fast facts. An Amiable-Expressive wants warm stories. Read the primary type first, then blend in the secondary. Flexibility is the superpower.': 'La mayor\u00eda de las personas son una mezcla de dos tipos. Un Conductor-Anal\u00edtico quiere hechos r\u00e1pidos. Un Amable-Expresivo quiere historias c\u00e1lidas. Lee el tipo primario primero, luego integra el secundario. La flexibilidad es el superpoder.',
    'The golden rule of sales is not \'treat everyone the same.\' It is \'treat everyone how THEY want to be treated.\' Personality types show you the way.': 'La regla de oro de las ventas no es \'trata a todos igual.\' Es \'trata a todos como ELLOS quieren ser tratados.\' Los tipos de personalidad te muestran el camino.',

    # Quiz connect-8
    'Which approach works best with an Analytical buyer?': '\u00bfQu\u00e9 enfoque funciona mejor con un comprador Anal\u00edtico?',
    'High-energy enthusiasm and storytelling': 'Entusiasmo de alta energ\u00eda y narraci\u00f3n de historias',
    'Facts, evidence, and respect for their decision-making process': 'Hechos, evidencia y respeto por su proceso de toma de decisiones',
    'Fast, direct results with no small talk': 'Resultados r\u00e1pidos y directos sin pl\u00e1tica ligera',
    'Emotional connection and warm rapport': 'Conexi\u00f3n emocional y rapport c\u00e1lido',
    'Analytical buyers want facts, evidence, and proof. They need to understand how things work before committing. Respect their thoroughness and give them space to decide.': 'Los compradores Anal\u00edticos quieren hechos, evidencia y pruebas. Necesitan entender c\u00f3mo funcionan las cosas antes de comprometerse. Respeta su minuciosidad y d\u00e9les espacio para decidir.',
    'How should you handle a Driver personality type?': '\u00bfC\u00f3mo debes manejar un tipo de personalidad Conductor?',
    'Build extensive rapport before pitching': 'Construir rapport extenso antes de presentar',
    'Be fast, direct, and results-focused with binary choices': 'Ser r\u00e1pido, directo y enfocado en resultados con opciones binarias',
    'Tell stories and paint pictures': 'Contar historias y pintar cuadros',
    'Give them lots of detailed information': 'Darles mucha informaci\u00f3n detallada',
    'Drivers are time-pressed and decisive. They want quick results, clear options, and respect for their schedule. Skip the small talk, get to the demo and close fast.': 'Los Conductores tienen poco tiempo y son decisivos. Quieren resultados r\u00e1pidos, opciones claras y respeto por su agenda. Omite la pl\u00e1tica ligera, ve a la demostraci\u00f3n y cierra r\u00e1pido.',
    'Why is it important to adapt your style to different personality types?': '\u00bfPor qu\u00e9 es importante adaptar tu estilo a diferentes tipos de personalidad?',
    'It is not important \u2014 one pitch works for everyone': 'No es importante \u2014 una presentaci\u00f3n le funciona a todos',
    'Because different types respond to different communication styles, and mismatching creates resistance': 'Porque diferentes tipos responden a diferentes estilos de comunicaci\u00f3n, y el desajuste crea resistencia',
    'Because the manager requires it': 'Porque el gerente lo requiere',
    'Because it makes the job more interesting': 'Porque hace el trabajo m\u00e1s interesante',
    'Different personality types process information and make decisions differently. Using the wrong approach with the wrong type creates resistance \u2014 like speaking the wrong language. Adaptation is the key to precision selling.': 'Diferentes tipos de personalidad procesan informaci\u00f3n y toman decisiones de forma distinta. Usar el enfoque equivocado con el tipo equivocado crea resistencia \u2014 como hablar el idioma equivocado. La adaptaci\u00f3n es la clave de la venta de precisi\u00f3n.',
}
